# Clustering Configuration
# Parameters for hyperparameter search across different clustering algorithms

# Model settings
model:
  path: "/path/to/wav2vec2/model"  # TODO: Update with actual model path
  batch_size: 16
  max_length: 32000
  device: "auto"  # "cuda", "cpu", or "auto"

# Dataset settings
dataset:
  audio_column: "segment_file"  # Column name containing audio file paths

# UMAP parameters (common across all algorithms)
umap:
  n_neighbors: [5, 15, 30]
  min_dist: [0.0, 0.1]
  n_components: [2, 5, 10]
  random_state: 42

# Algorithm-specific parameters
algorithms:
  kmeans:
    n_clusters: [5, 6, 7, 8, 9, 10]
    init: ["k-means++", "random"]
    random_state: [42]
  
  spectral:
    
    n_clusters: [5, 6, 7, 8, 9, 10]
    affinity: ["rbf", "nearest_neighbors"]
    n_neighbors: [10, 15]
    assign_labels: ["kmeans", "discretize"]
    random_state: [42]
  
  agglomerative:
    
    n_clusters: [5, 6, 7, 8, 9]
    linkage: ["ward", "complete", "average"]

# Evaluation settings
evaluation:
  metric: "silhouette"
  dual_phase: true  # Use dual-phase evaluation (mean + best absolute)

# Output settings
output:
  save_results_summary: true
  display_top_configs: 5
  verbose: true