# Clustering Hyperparameter Search Configuration
# Example configuration for unified clustering analysis (K-means, Agglomerative, Spectral)

clustering:
  # Data configuration
  data_file: "data/segmented_audio_data.csv"  # CSV file with 'path' column for audio files
  model_path: "models/final_model_freeze_good"  # Path to fine-tuned Wav2Vec2 model
  output_dir: "results/clustering"  # Output directory for results and visualizations
  
  # Embedding extraction parameters
  max_length: 32000  # Maximum audio length in samples (2 seconds at 16kHz)
  batch_size: 16  # Batch size for embedding extraction
  sampling_rate: 16000  # Audio sampling rate
  
  # Clustering parameters
  k_range: [5, 6, 7, 8, 9, 10]  # Range of cluster numbers to test
  random_state: 42  # Random seed for reproducibility
  
  # Evaluation
  metric: "silhouette"  # Clustering evaluation metric (currently only silhouette supported)
  
  # Output options
  create_plots: true  # Generate visualization plots
  save_results: true  # Save detailed results to files

# Notes:
# - The data_file should be a CSV with columns: 'path' (audio file paths), 'speaker', 'text', etc.
# - The model_path should point to a fine-tuned Wav2Vec2 model directory
# - Results will include:
#   * clustering_hyperparameter_results.csv: All configurations and scores
#   * best_clustering_config.yaml: Best configuration found
#   * clustering_summary.txt: Human-readable summary
#   * Visualization plots (if create_plots: true)

# Example usage:
# python -m src.clustering.hyperparameter_search --config clustering_config.yaml
# python -m src.clustering.hyperparameter_search --config clustering_config.yaml --k-range 3 4 5 6 7
# python -m src.clustering.hyperparameter_search --config clustering_config.yaml --data-file my_data.csv --output-dir my_results/