# LLM Cluster Analysis Configuration
# Configuration for comprehensive cluster analysis including weight optimization,
# LLM emotion analysis, NLP evaluation, and audio export

llm_analysis:
  # Data configuration
  data_file: "data/clustered_data.csv"  # CSV file with clustered audio data
  output_dir: "results/llm_analysis"    # Output directory for all results
  
  # Weight optimization for representative element selection
  n_representative_points: 10     # Number of representative points per cluster
  weight_steps: 11               # Number of weight combinations to test (0.0 to 1.0)
  weight_distance: 0.6           # Default weight for distance from centroid
  weight_duration: 0.4           # Default weight for audio duration
  
  # LLM configuration
  llm_model: "gemma3:12b-it-q4_K_M"  # model for emotion analysis
  analysis_type: "short"             # "short" (structured) or "detailed" (narrative)
  
  # NLP evaluation metrics
  enable_nlp_evaluation: true     # Enable BLEU, ROUGE, BERTScore evaluation
  evaluation_mode: "both"         # "individual", "concatenated", or "both"
  
  # Audio file export
  enable_audio_export: true       # Export representative audio files
  create_zip_archive: true        # Create ZIP archive of all audio files
  
  # Output options
  save_results: true              # Save all analysis results to files
  create_google_forms_data: true  # Create Google Forms compatible data file

# Notes:
# - The data_file should be a CSV with columns: 'cluster', 'path', 'text', 'duration', 'distance_from_centroid'
# - LLM analysis requires Ollama running locally with the specified model
# - NLP evaluation requires the 'evaluate' package and internet connection for some metrics
# - Audio export requires readable audio files at the paths specified in the CSV
# - Results will include:
#   * cluster_analyses.csv: LLM emotion analyses for each cluster
#   * nlp_evaluation_*.csv: NLP evaluation metrics
#   * exported_audio/: Organized audio files and metadata
#   * google_forms_data.csv: Data formatted for human evaluation

# Example usage:
# python -m src.analysis.llm_analyzer --config llm_analysis_config.yaml
# python -m src.analysis.llm_analyzer --config llm_analysis_config.yaml --data-file my_data.csv --output-dir my_results/
# python -m src.analysis.llm_analyzer --config llm_analysis_config.yaml --analysis-type detailed --no-audio-export