language: italian

preprocessing:
  filter_unknown_speakers: true
  min_duration: 1.5
  clean_text: true

embedding:
  model: "paraphrase-multilingual-MiniLM-L12-v2"

umap:
  k_min: 15
  k_max: 100
  n_components: 5

clustering:
  algorithm: kmeans  # or hdbscan

vectorizer:
  language: italian
  min_df: 2
  ngram_range: [1, 2]

llm:
  base_url: "http://localhost:11434/v1"
  api_key: "ollama"
  model: "gemma3:12b-it-q4_K_M"
  

topic_search:
  enable_search: true
  search_keywords: ["infanzia", "viaggio"]
  top_n: 5

